export const authConstants = {
    REGISTER_REQUEST: 'AUTH_REGISTER_REQUEST',
    REGISTER_SUCCESS: 'AUTH_REGISTER_SUCCESS',
    REGISTER_FAILURE: 'AUTH_REGISTER_FAILURE',

    LOGIN_REQUEST: 'AUTH_LOGIN_REQUEST',
    LOGIN_SUCCESS: 'AUTH_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'AUTH_LOGIN_FAILURE',
    
    LOGOUT_SUCCESS: 'AUTH_LOGOUT_SUCCESS',
    LOGOUT_FAILURE: 'AUTH_LOGOUT_FASILURE',

};

export const plannerConstants = {
    SELECT_PLAYER_NUMBER: 'SELECT_PLAYER_NUMBER',
    SELECT_ROUND_TIME: 'SELECT_ROUND_TIME',
};

export const gameConstants = {
    GAME_CREATE_REQUEST: 'GAME_CREATE_REQUEST',
    GAME_CREATE_SUCCESS: 'GAME_CREATE_SUCCESS',
    GAME_CREATE_FAILURE: 'GAME_CREATE_FAILURE',

    GAME_GET_REQUEST: 'GAME_GET_REQUEST',
    GAME_GET_SUCCESS: 'GAME_GET_SUCCESS',
    GAME_GET_FAILURE: 'GAME_GET_FAILURE',

    NEW_SEAT: 'NEW_SEAT',
};

export const chatConstants = {
    CHAT_NEW_MESSAGE: 'CHAT_NEW_MESSAGE',
};

export const handConstants = {
    MY_CARDS_CHANGE: 'MY_CARDS_CHANGE',
};